export {default as Home} from './Home/Home'
export {default as Profile} from './Profile/Profile' 
export {default as Broswer} from './Browse/Broswer'
export {default as Feature} from './Browse/Feature'
export {default as Side} from './Browse/Side'
export {default as stream} from'./Browse/Stream'
export {default as Prof} from './Profile/Prof'
export {default as Clips} from './Profile/Clips'
export {default as Details} from './details/Details'